/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.verificadordeprecios;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author davox
 */
public class VentanaVerificador extends javax.swing.JFrame {
private String codigo = "";
    /**
     * Creates new form VentanaVerificador
     */
    public VentanaVerificador() {
        initComponents();
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize().width, Toolkit.getDefaultToolkit().getScreenSize().height);

        this.setLayout(null);
        setDefault();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre = new javax.swing.JLabel();
        labelLogo = new javax.swing.JLabel();
        labelInstrucciones = new javax.swing.JLabel();
        labelGif = new javax.swing.JLabel();
        labelProducto = new javax.swing.JLabel();
        labelStock = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        labelImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        labelNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        labelNombre.setMaximumSize(new java.awt.Dimension(409000, 409000));
        labelNombre.setMinimumSize(new java.awt.Dimension(32, 32));
        labelNombre.setPreferredSize(new java.awt.Dimension(500, 32));

        labelLogo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        labelLogo.setMaximumSize(new java.awt.Dimension(409000, 409000));
        labelLogo.setMinimumSize(new java.awt.Dimension(32, 32));
        labelLogo.setPreferredSize(new java.awt.Dimension(500, 32));

        labelInstrucciones.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        labelInstrucciones.setMaximumSize(new java.awt.Dimension(409000, 409000));
        labelInstrucciones.setMinimumSize(new java.awt.Dimension(32, 32));
        labelInstrucciones.setPreferredSize(new java.awt.Dimension(500, 32));

        labelGif.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        labelGif.setMaximumSize(new java.awt.Dimension(409000, 409000));
        labelGif.setMinimumSize(new java.awt.Dimension(32, 32));
        labelGif.setPreferredSize(new java.awt.Dimension(500, 32));

        labelProducto.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        labelProducto.setMaximumSize(new java.awt.Dimension(409000, 409000));
        labelProducto.setMinimumSize(new java.awt.Dimension(32, 32));
        labelProducto.setPreferredSize(new java.awt.Dimension(500, 32));

        labelStock.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        labelStock.setMaximumSize(new java.awt.Dimension(409000, 409000));
        labelStock.setMinimumSize(new java.awt.Dimension(32, 32));
        labelStock.setPreferredSize(new java.awt.Dimension(500, 32));

        labelPrecio.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        labelPrecio.setMaximumSize(new java.awt.Dimension(409000, 409000));
        labelPrecio.setMinimumSize(new java.awt.Dimension(32, 32));
        labelPrecio.setPreferredSize(new java.awt.Dimension(500, 32));

        labelImagen.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        labelImagen.setMaximumSize(new java.awt.Dimension(409000, 409000));
        labelImagen.setMinimumSize(new java.awt.Dimension(32, 32));
        labelImagen.setPreferredSize(new java.awt.Dimension(500, 32));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(402, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(labelInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(labelGif, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(382, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(labelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(labelStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(labelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(186, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(labelInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(268, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(labelGif, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(148, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(labelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(248, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(labelStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(238, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(labelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(228, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(218, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
    if (evt.getKeyCode() != 10) {
            codigo += evt.getKeyChar();
        } else {

            try {

                Connection con = null;

                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tienda", "root", "");
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT nombreProducto, precioProducto, cantidadProducto, imagenProducto FROM productos WHERE numeroProducto = " + codigo);

                if (rs.next()) {

                    setProduct();
                    labelProducto.setText(rs.getString(1));
                    labelPrecio.setText(Integer.toString(rs.getInt(2)) + " pesos");
                    labelStock.setText(Integer.toString(rs.getInt(3)) + " unidades");
                    this.invalidate();
                    this.validate();
                    this.repaint();

                    URL url;
                    try {
                        url = new URL(rs.getString(4));
                        Image image = ImageIO.read(url);
                        Image trueImage = image.getScaledInstance(-1, 200, 1);
                        ImageIcon icon = new ImageIcon(trueImage);

                        labelImagen.setIcon(icon);
                        labelImagen.setSize(trueImage.getWidth(null), 200);
                        this.invalidate();
                        this.validate();
                        this.repaint();
                    } catch (MalformedURLException ex) {
                        JOptionPane.showMessageDialog(null, ex.toString());
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, ex.toString());
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Producto no encontrado, llame a personal autorizado");
                }
                Thread.sleep(8000);
                setDefault();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.toString());
            } catch (InterruptedException ex) {
                JOptionPane.showMessageDialog(null, ex.toString());
            }

            codigo = "";

        }    // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVerificador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVerificador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVerificador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVerificador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVerificador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelGif;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JLabel labelInstrucciones;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelProducto;
    private javax.swing.JLabel labelStock;
    // End of variables declaration//GEN-END:variables

    public void setDefault() {

        int width = this.getWidth();
        int height = this.getHeight();
        labelImagen.setIcon(null);
        labelProducto.setText("");
        labelStock.setText("");
        labelPrecio.setText("");
        labelNombre.setLocation(this.getWidth() / 2 - labelNombre.getWidth() / 2, 0);
        labelLogo.setLocation(this.getWidth() / 2 - labelLogo.getWidth() / 2, labelNombre.getLocation().y + labelNombre.getHeight());
        labelNombre.setText("Super del Sur");
        labelInstrucciones.setLocation((int) (this.getWidth() * 0.33), (int) (height * 0.6));
        labelInstrucciones.setText("<html>" + "Pase el codigo por el lector para buscar el producto" + "</html>");
        labelGif.setLocation((int) (labelInstrucciones.getLocation().x + (int) labelInstrucciones.getWidth() * 0.3), (int) (labelInstrucciones.getLocation().y - labelInstrucciones.getHeight() * 1.2));
        labelGif.setText("<html><img src='/com/mycompany/verificadordeprecios/carrito.png'>");
        this.invalidate();
        this.validate();
        this.repaint();
    }

    public void setProduct() {
        labelInstrucciones.setText("");
        labelGif.setIcon(null);
        labelImagen.setLocation((int) (this.getWidth() * 0.3), (int) (this.getHeight() * 0.4));
        labelProducto.setLocation((int) (labelImagen.getLocation().x * 1.05), labelImagen.getLocation().y);
        labelPrecio.setLocation((int) (labelProducto.getLocation().x * 0.9), labelProducto.getLocation().y + labelProducto.getHeight());
        labelStock.setLocation((int) (labelProducto.getLocation().x * 0.9), labelProducto.getLocation().y + (labelProducto.getHeight() * 2));
        this.invalidate();
        this.validate();
        this.repaint();
    }
}
